version: '3'
services: 
  db:
    container_name: db
    image: 'postgres:14'
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: potential-crud
    volumes: 
      - ./pfdata:/var/lib/postgresql/data
    ports:
       - "5432:5432" 
  